language: perl
services:
  - redis-server
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
before_install:
  cpanm Minilla Test::CPAN::Meta Test::Pod Test::MinimumVersion::Fast
script:
  minil test --all
